# ONEDIGIWEB Service Page Generator v2 â€” emoji-safe version
$baseDir = "c:\Users\vikky\OneDrive\Desktop\OneDrive\Desktop\digital"

$pages = @(
  @{ slug="seo-services"; icon="[SEO]"; title="SEO Services India | Best SEO Company | ONEDIGIWEB"; h1="Best SEO Services in India"; h2="Rank #1 on Google with Data-Driven Search Engine Optimization"; meta="ONEDIGIWEB offers professional SEO services in India. Local SEO, National SEO, Technical SEO, Link Building and SEO Audit. Get more traffic and leads from Google."; keyword="SEO Company India, SEO Services India, Best SEO Agency"; sname="SEO Services"; services="Local SEO,National SEO,Ecommerce SEO,Technical SEO,SEO Audit,Link Building,On-Page SEO,Off-Page SEO" },
  @{ slug="digital-marketing-services"; icon="[DM]"; title="Digital Marketing Agency India | ONEDIGIWEB Marketing Solution"; h1="Best Digital Marketing Agency in India"; h2="Grow Your Business With Data-Driven Digital Marketing Strategies"; meta="ONEDIGIWEB is a top digital marketing agency in India offering SEO, Google Ads, Social Media Marketing, Content Marketing and Lead Generation services."; keyword="Digital Marketing Agency India, Online Marketing Company, Digital Marketing Services"; sname="Digital Marketing"; services="Search Engine Marketing,Social Media Marketing,Google Ads,Meta Ads,Email Marketing,Content Marketing,Influencer Marketing,Brand Strategy" },
  @{ slug="google-ads-services"; icon="[ADS]"; title="Google Ads Agency India | PPC Management Services | ONEDIGIWEB"; h1="Google Ads Management Services in India"; h2="Get Maximum ROI With Professional Google Ads and PPC Campaigns"; meta="ONEDIGIWEB provides expert Google Ads management in India. Search Ads, Display Ads, Shopping Ads, YouTube Ads and Remarketing campaigns that deliver results."; keyword="Google Ads Agency India, PPC Management Services, Google AdWords Expert"; sname="Google Ads Management"; services="Search Ads,Display Ads,Shopping Ads,YouTube Ads,Remarketing,Performance Max,App Campaigns,Local Campaigns" },
  @{ slug="social-media-marketing"; icon="[SMM]"; title="Social Media Marketing Agency India | Instagram Facebook Ads | ONEDIGIWEB"; h1="Social Media Marketing Services in India"; h2="Build Your Brand and Drive Sales With Powerful Social Media Marketing"; meta="ONEDIGIWEB offers social media marketing in India. Instagram, Facebook, LinkedIn, YouTube marketing and paid social ads that grow your brand online."; keyword="Social Media Marketing Agency India, Instagram Marketing, Facebook Marketing Services"; sname="Social Media Marketing"; services="Instagram Marketing,Facebook Marketing,LinkedIn Marketing,YouTube Marketing,Twitter Marketing,Social Media Ads,Content Creation,Community Management" },
  @{ slug="website-development"; icon="[WEB]"; title="Website Development Company India | Professional Web Design | ONEDIGIWEB"; h1="Professional Website Development Company in India"; h2="Fast, Mobile-First and SEO-Optimized Websites That Convert Visitors Into Customers"; meta="ONEDIGIWEB builds professional websites in India. WordPress, Custom websites, Landing pages, Business and Portfolio sites. Mobile-first, SEO-friendly and fast loading."; keyword="Website Development Company India, Web Design Agency, Professional Website Design"; sname="Website Development"; services="Business Website,WordPress Development,Landing Pages,Portfolio Website,Hospital Website,School Website,Real Estate Website,News Portal" },
  @{ slug="wordpress-development"; icon="[WP]"; title="WordPress Development Services India | WP Expert | ONEDIGIWEB"; h1="WordPress Development Services in India"; h2="Custom WordPress Websites, Themes and Plugin Development"; meta="ONEDIGIWEB offers expert WordPress development in India. Custom themes, plugin development, WooCommerce, WordPress speed optimization and maintenance services."; keyword="WordPress Development India, WordPress Expert, Custom WordPress Website"; sname="WordPress Development"; services="Custom WordPress Theme,Plugin Development,WooCommerce Setup,WordPress Speed Optimization,WordPress Security,WordPress Migration,WordPress Maintenance,WordPress SEO" },
  @{ slug="ecommerce-development"; icon="[SHOP]"; title="Ecommerce Website Development India | Online Store | ONEDIGIWEB"; h1="Ecommerce Website Development in India"; h2="Build a Powerful Online Store That Sells 24 Hours a Day"; meta="ONEDIGIWEB builds professional ecommerce websites in India. WooCommerce, Shopify, custom stores with payment gateway integration and inventory management."; keyword="Ecommerce Website Development India, Online Store Development, WooCommerce Developer"; sname="Ecommerce Development"; services="WooCommerce Development,Shopify Development,Custom Ecommerce,Payment Gateway Integration,Multi-vendor Marketplace,Ecommerce SEO,Mobile Ecommerce App,Inventory Management" },
  @{ slug="shopify-development"; icon="[SHOPIFY]"; title="Shopify Development Services India | Shopify Expert | ONEDIGIWEB"; h1="Shopify Store Development Services in India"; h2="Launch and Grow Your Shopify Store With Expert Shopify Developers"; meta="ONEDIGIWEB offers expert Shopify development in India. Custom Shopify themes, store setup, apps integration, Shopify SEO and Shopify Plus development."; keyword="Shopify Developer India, Shopify Store Setup, Shopify Expert India"; sname="Shopify Development"; services="Shopify Store Setup,Custom Shopify Theme,Shopify App Integration,Shopify SEO,Shopify Speed Optimization,Shopify Migration,Shopify Plus,Dropshipping Setup" },
  @{ slug="app-development"; icon="[APP]"; title="Mobile App Development Company India | iOS Android App | ONEDIGIWEB"; h1="Mobile App Development Company in India"; h2="Build Powerful iOS and Android Apps That Grow Your Business"; meta="ONEDIGIWEB develops professional mobile apps in India. Native iOS, Android, React Native and Flutter apps for startups, businesses and enterprises."; keyword="App Development Company India, Mobile App Developer, iOS Android App Development"; sname="Mobile App Development"; services="iOS App Development,Android App Development,React Native App,Flutter App,Hybrid App,PWA Development,App UI/UX Design,App Maintenance" },
  @{ slug="graphic-design-services"; icon="[DESIGN]"; title="Graphic Design Services India | Logo and Branding | ONEDIGIWEB"; h1="Professional Graphic Design Services in India"; h2="Creative Design Solutions That Make Your Brand Stand Out"; meta="ONEDIGIWEB offers professional graphic design in India. Logo design, brand identity, social media graphics, brochures, packaging and marketing materials."; keyword="Graphic Design Services India, Logo Design Company, Brand Identity Design"; sname="Graphic Design"; services="Logo Design,Brand Identity,Social Media Graphics,Brochure Design,Business Card Design,Packaging Design,Infographic Design,Marketing Materials" },
  @{ slug="lead-generation-services"; icon="[LEADS]"; title="Lead Generation Services India | B2B B2C Leads | ONEDIGIWEB"; h1="Lead Generation Services in India"; h2="Get High-Quality Leads That Convert Into Real Customers"; meta="ONEDIGIWEB provides professional lead generation in India. B2B leads, B2C leads, real estate, insurance and education leads via Google Ads, SEO and social media."; keyword="Lead Generation Services India, B2B Lead Generation, Sales Lead Generation"; sname="Lead Generation"; services="Google Ads Lead Gen,Facebook Lead Ads,LinkedIn B2B Leads,SEO Lead Generation,Landing Page Optimization,Email Lead Campaigns,WhatsApp Lead Funnel,CRM Integration" },
  @{ slug="local-seo-services"; icon="[LOCAL]"; title="Local SEO Services India | Google My Business | ONEDIGIWEB"; h1="Local SEO Services in India"; h2="Dominate Local Search Results and Get More Customers in Your City"; meta="ONEDIGIWEB offers local SEO services in India. Google My Business optimization, local citations, local keyword ranking, link building and reputation management."; keyword="Local SEO Services India, Google My Business Expert, Local Search Optimization"; sname="Local SEO Services"; services="Google My Business Optimization,Local Keyword Research,Local Citations,NAP Consistency,Local Link Building,Review Management,Local Landing Pages,Geo-Targeted Ads" }
)

function Make-Page {
  param($p)
  $svList = ($p.services -split ",") | ForEach-Object { "      <div class=`"sv-item`"><span>&#10003;</span> $($_.Trim())</div>" }
  $svHTML = $svList -join "`n"
  
  $html = "<!DOCTYPE html>`n<html lang=`"en`">`n<head>`n"
  $html += "  <meta charset=`"UTF-8`" />`n"
  $html += "  <meta name=`"viewport`" content=`"width=device-width, initial-scale=1.0`" />`n"
  $html += "  <!-- ============================================================`n"
  $html += "       MARKETING INTEGRATIONS (Analytics, AdSense, Pinterest, Ads)`n"
  $html += "  ============================================================ -->`n"
  $html += "  <!-- Google Tag (gtag.js) - Google Analytics & Google Ads -->`n"
  $html += "  <script async src=`"https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX`"></script>`n"
  $html += "  <script>`n"
  $html += "    window.dataLayer = window.dataLayer || [];`n"
  $html += "    function gtag(){dataLayer.push(arguments);}`n"
  $html += "    gtag('js', new Date());`n"
  $html += "    gtag('config', 'G-XXXXXXXXXX'); // Replace with Google Analytics Measurement ID`n"
  $html += "    gtag('config', 'AW-YYYYYYYYY');  // Replace with Google Ads Conversion ID`n"
  $html += "  </script>`n"
  $html += "  <!-- Google AdSense -->`n"
  $html += "  <script async src=`"https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-ZZZZZZZZZZZZZZZZ`" crossorigin=`"anonymous`"></script>`n"
  $html += "  <!-- Pinterest Tag -->`n"
  $html += "  <script>`n"
  $html += "    !function(e){if(!window.pintrk){window.pintrk=function(){window.pintrk.queue.push(Array.prototype.slice.call(arguments))};var n=window.pintrk;n.queue=[],n.version=`"3.0`";var t=document.createElement(`"script`");t.async=!0,t.src=e;var r=document.getElementsByTagName(`"script`")[0];r.parentNode.insertBefore(t,r)}}(`"https://s.pinterest.com/js/pinit.js`");`n"
  $html += "    pintrk('load', 'PARTNER_ID'); // Replace with Pinterest Partner ID`n"
  $html += "    pintrk('page');`n"
  $html += "  </script>`n"
  $html += "  <noscript>`n"
  $html += "    <img height=`"1`" width=`"1`" style=`"display:none;`" alt=`"`" src=`"https://ct.pinterest.com/v3/?event=init&tid=PARTNER_ID&noscript=1`" />`n"
  $html += "  </noscript>`n"
  $html += "  <!-- ============================================================ -->`n"
  $html += "  <title>$($p.title)</title>`n"
  $html += "  <meta name=`"description`" content=`"$($p.meta)`" />`n"
  $html += "  <meta name=`"keywords`" content=`"$($p.keyword)`" />`n"
  $html += "  <meta name=`"robots`" content=`"index, follow`" />`n"
  $html += "  <meta name=`"author`" content=`"ONEDIGIWEB Marketing Solution`" />`n"
  $html += "  <meta name=`"theme-color`" content=`"#5B21B6`" />`n"
  $html += "  <link rel=`"canonical`" href=`"https://onedigiweb.com/$($p.slug).html`" />`n"
  $html += "  <link rel=`"icon`" type=`"image/x-icon`" href=`"assets/favicon/favicon.ico`" />`n"
  $html += "  <link rel=`"icon`" type=`"image/png`" sizes=`"32x32`" href=`"assets/favicon/favicon-32x32.png`" />`n"
  $html += "  <link rel=`"apple-touch-icon`" sizes=`"180x180`" href=`"assets/favicon/apple-touch-icon.png`" />`n"
  $html += "  <meta property=`"og:title`" content=`"$($p.h1) | ONEDIGIWEB`" />`n"
  $html += "  <meta property=`"og:description`" content=`"$($p.meta)`" />`n"
  $html += "  <meta property=`"og:image`" content=`"assets/images/og-image.png`" />`n"
  $html += "  <meta property=`"og:type`" content=`"website`" />`n"
  $html += "  <meta name=`"twitter:card`" content=`"summary_large_image`" />`n"
  $html += "  <link rel=`"preconnect`" href=`"https://fonts.googleapis.com`" />`n"
  $html += "  <link rel=`"preconnect`" href=`"https://fonts.gstatic.com`" crossorigin />`n"
  $html += "  <link href=`"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&family=Inter:wght@300;400;500;600;700&display=swap`" rel=`"stylesheet`" />`n"
  $html += "  <link rel=`"stylesheet`" href=`"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css`" crossorigin=`"anonymous`" />`n"
  $html += "  <link rel=`"stylesheet`" href=`"style.css?v=2.1`" />`n"
  $html += "  <script type=`"application/ld+json`">`n"
  $html += "  {`"@context`":`"https://schema.org`",`"@type`":`"BreadcrumbList`",`"itemListElement`":[{`"@type`":`"ListItem`",`"position`":1,`"name`":`"Home`",`"item`":`"https://onedigiweb.com/`"},{`"@type`":`"ListItem`",`"position`":2,`"name`":`"Services`",`"item`":`"https://onedigiweb.com/#services`"},{`"@type`":`"ListItem`",`"position`":3,`"name`":`"$($p.sname)`",`"item`":`"https://onedigiweb.com/$($p.slug).html`"}]}`n"
  $html += "  </script>`n"
  $html += "  <script type=`"application/ld+json`">`n"
  $html += "  {`"@context`":`"https://schema.org`",`"@type`":`"Service`",`"name`":`"$($p.sname)`",`"provider`":{`"@type`":`"LocalBusiness`",`"name`":`"ONEDIGIWEB Marketing Solution`",`"telephone`":`"+918512821525`",`"email`":`"onedigiweb@gmail.com`"},`"description`":`"$($p.meta)`",`"areaServed`":`"India`"}`n"
  $html += "  </script>`n"
  $html += "  <script type=`"application/ld+json`">`n"
  $html += "  {`"@context`":`"https://schema.org`",`"@type`":`"FAQPage`",`"mainEntity`":[{`"@type`":`"Question`",`"name`":`"What is $($p.sname)?`",`"acceptedAnswer`":{`"@type`":`"Answer`",`"text`":`"$($p.sname) helps businesses improve online visibility and reach more customers through targeted digital strategies.`"}},{`"@type`":`"Question`",`"name`":`"How much does $($p.sname) cost?`",`"acceptedAnswer`":{`"@type`":`"Answer`",`"text`":`"Pricing starts from Rs. 9,999/month. Contact ONEDIGIWEB for a free consultation and custom quote.`"}}]}`n"
  $html += "  </script>`n"
  $html += "  <style>`n"
  $html += "    .sp-hero{background:linear-gradient(135deg,#0F172A 0%,#1E1035 50%,#0C1340 100%);padding:120px 0 80px;}`n"
  $html += "    .sp-breadcrumb{display:flex;align-items:center;gap:8px;font-size:13px;color:rgba(255,255,255,0.5);margin-bottom:20px;flex-wrap:wrap;}`n"
  $html += "    .sp-breadcrumb a{color:rgba(255,255,255,0.5);transition:color .2s;}`n"
  $html += "    .sp-breadcrumb a:hover{color:var(--accent);}`n"
  $html += "    .sp-breadcrumb span{color:rgba(255,255,255,0.3);}`n"
  $html += "    .sp-hero-badge{display:inline-flex;align-items:center;gap:8px;padding:6px 16px;border-radius:50px;background:rgba(255,255,255,0.07);border:1px solid rgba(255,255,255,0.12);color:rgba(255,255,255,0.8);font-size:13px;font-weight:500;margin-bottom:20px;}`n"
  $html += "    .sp-hero-icon{font-size:18px;font-weight:800;color:var(--accent);background:rgba(6,182,212,0.1);padding:8px 16px;border-radius:8px;margin-bottom:16px;display:inline-block;}`n"
  $html += "    .sp-hero h1{font-family:var(--font);font-size:clamp(28px,5vw,56px);font-weight:900;color:white;line-height:1.15;margin-bottom:16px;letter-spacing:-0.5px;}`n"
  $html += "    .sp-hero h2{font-size:clamp(15px,2.5vw,21px);color:rgba(255,255,255,0.7);font-weight:500;line-height:1.6;margin-bottom:28px;max-width:640px;}`n"
  $html += "    .sp-hero-btns{display:flex;gap:12px;flex-wrap:wrap;}`n"
  $html += "    .sp-services{background:var(--light);padding:80px 0;}`n"
  $html += "    .sv-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;}`n"
  $html += "    .sv-item{display:flex;align-items:center;gap:10px;padding:16px 18px;background:white;border:1px solid var(--border);border-radius:12px;font-size:15px;font-weight:500;color:var(--dark);transition:var(--ease);}`n"
  $html += "    .sv-item:hover{border-color:var(--p2);color:var(--p1);transform:translateY(-3px);box-shadow:var(--sh-card);}`n"
  $html += "    .sv-item span{color:var(--p2);font-weight:700;}`n"
  $html += "    .sp-why{background:white;padding:80px 0;}`n"
  $html += "    .sp-why-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:24px;}`n"
  $html += "    .sp-why-card{padding:28px;border-radius:var(--r-lg);border:1px solid var(--border);text-align:center;transition:var(--ease);}`n"
  $html += "    .sp-why-card:hover{border-color:rgba(91,33,182,0.3);box-shadow:var(--sh-hover);transform:translateY(-4px);}`n"
  $html += "    .sp-why-icon{font-size:36px;margin-bottom:12px;}`n"
  $html += "    .sp-why-card h3{font-family:var(--font);font-size:17px;font-weight:700;color:var(--dark);margin-bottom:8px;}`n"
  $html += "    .sp-why-card p{font-size:14px;color:var(--gray);line-height:1.6;}`n"
  $html += "    .sp-cta-sec{background:var(--g-main);padding:80px 0;text-align:center;}`n"
  $html += "    .sp-cta-sec h2{font-family:var(--font);font-size:clamp(24px,4vw,42px);font-weight:900;color:white;margin-bottom:12px;}`n"
  $html += "    .sp-cta-sec p{font-size:18px;color:rgba(255,255,255,0.75);margin-bottom:32px;}`n"
  $html += "    .sp-cta-btns{display:flex;justify-content:center;gap:14px;flex-wrap:wrap;}`n"
  $html += "    .btn-white{background:white;color:var(--p1);padding:15px 32px;border-radius:50px;font-family:var(--font);font-size:16px;font-weight:700;transition:var(--ease);display:inline-block;}`n"
  $html += "    .btn-white:hover{transform:translateY(-3px);box-shadow:0 8px 30px rgba(0,0,0,0.2);}`n"
  $html += "    .sp-footer-mini{background:var(--dark);padding:30px 0;text-align:center;}`n"
  $html += "    .sp-footer-mini p{color:rgba(255,255,255,0.75);font-size:13px;}`n"
  $html += "    .sp-footer-mini a{color:var(--accent);}`n"
  $html += "    @media(max-width:768px){.sv-grid{grid-template-columns:1fr 1fr;}.sp-why-grid{grid-template-columns:1fr;}.sp-hero-btns{flex-direction:column;}}`n"
  $html += "    @media(max-width:480px){.sv-grid{grid-template-columns:1fr;}}`n"
  $html += "  </style>`n"
  $html += "</head>`n<body>`n`n"

  # Header
  $html += "<!-- COMPONENT: HEADER -->`n"
  $html += "<header class=`"header`" id=`"header`">`n"
  $html += "  <nav class=`"navbar container`">`n"
  $html += "    <!-- Logo -->`n"
  $html += "    <a href=`"index.html`" class=`"logo-link`"><img src=`"assets/images/onedigiweb-marketing-solution-logo.png`" alt=`"ONEDIGIWEB Marketing Solution Logo`" title=`"ONEDIGIWEB Marketing Solution`" width=`"260`" height=`"74`" class=`"logo-img`"></a>`n"
  $html += "    <!-- Nav Menu -->`n"
  $html += "    <ul class=`"nav-menu`" id=`"navMenu`" role=`"menubar`">`n"
  $html += "      <li class=`"nav-item`"><a href=`"index.html#home`" class=`"nav-link active`" role=`"menuitem`">Home</a></li>`n"
  $html += "<li class=`"nav-item has-mega`">`n"
  $html += "        <a href=`"#services`" class=`"nav-link nav-link-arrow`" role=`"menuitem`">Services</a>`n"
  $html += "                        <div class=`"mega-menu tabbed-mega-menu`" role=`"menu`">`n"
  $html += "          <div class=`"mega-inner container`">`n"
  $html += "            `n"
  $html += "            <!-- Top Category Tabs -->`n"
  $html += "            <div class=`"tmm-tabs-container`">`n"
  $html += "              <div class=`"tmm-tabs`">`n"
  $html += "                <button class=`"tmm-tab active`" data-target=`"tmm-seo`"><i class=`"fa-solid fa-magnifying-glass`"></i> SEO Services</button>`n"
  $html += "                <button class=`"tmm-tab`" data-target=`"tmm-dm`"><i class=`"fa-solid fa-bullhorn`"></i> Digital Marketing</button>`n"
  $html += "                <button class=`"tmm-tab`" data-target=`"tmm-web`"><i class=`"fa-solid fa-code`"></i> Website Development</button>`n"
  $html += "                <button class=`"tmm-tab`" data-target=`"tmm-app`"><i class=`"fa-solid fa-mobile-screen`"></i> App Marketing</button>`n"
  $html += "                <button class=`"tmm-tab`" data-target=`"tmm-cm`"><i class=`"fa-solid fa-pen-nib`"></i> Content Marketing</button>`n"
  $html += "                <button class=`"tmm-tab`" data-target=`"tmm-ppc`"><i class=`"fa-solid fa-mouse-pointer`"></i> Google Ads / PPC</button>`n"
  $html += "                <button class=`"tmm-tab`" data-target=`"tmm-ar`"><i class=`"fa-solid fa-chart-pie`"></i> Analytics & Reporting</button>`n"
  $html += "                <button class=`"tmm-tab`" data-target=`"tmm-gd`"><i class=`"fa-solid fa-bezier-curve`"></i> Graphic Design</button>`n"
  $html += "                <button class=`"tmm-tab`" data-target=`"tmm-sd`"><i class=`"fa-solid fa-laptop-code`"></i> Software Development</button>`n"
  $html += "              </div>`n"
  $html += "            </div>`n"
  $html += "`n"
  $html += "            <div class=`"tmm-body`">`n"
  $html += "              <!-- Left side: Services List -->`n"
  $html += "              <div class=`"tmm-content-area`">`n"
  $html += "                `n"
  $html += "                <!-- SEO -->`n"
  $html += "                <div class=`"tmm-content active`" id=`"tmm-seo`">`n"
  $html += "                  <div class=`"tmm-links-grid`">`n"
  $html += "                    <a href=`"seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-magnifying-glass-chart`"></i><span>SEO Services</span></a>`n"
  $html += "                    <a href=`"local-seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-map-location-dot`"></i><span>Local SEO</span></a>`n"
  $html += "                    <a href=`"seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-gears`"></i><span>Technical SEO</span></a>`n"
  $html += "                    <a href=`"seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-cart-arrow-down`"></i><span>Ecommerce SEO</span></a>`n"
  $html += "                    <a href=`"seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-building`"></i><span>Enterprise SEO</span></a>`n"
  $html += "                    <a href=`"seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-robot`"></i><span>AI SEO</span></a>`n"
  $html += "                    <a href=`"seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-stethoscope`"></i><span>SEO audit</span></a>`n"
  $html += "                    <a href=`"seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-link`"></i><span>Link Building</span></a>`n"
  $html += "                    <a href=`"seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-triangle-exclamation`"></i><span>Google Penalty Recovery</span></a>`n"
  $html += "                    <a href=`"seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-truck-fast`"></i><span>SEO Migration</span></a>`n"
  $html += "                    <a href=`"seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-language`"></i><span>Multilingual SEO</span></a>`n"
  $html += "                    <a href=`"seo-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-globe`"></i><span>International SEO</span></a>`n"
  $html += "                  </div>`n"
  $html += "                </div>`n"
  $html += "`n"
  $html += "                <!-- Digital Marketing -->`n"
  $html += "                <div class=`"tmm-content`" id=`"tmm-dm`">`n"
  $html += "                  <div class=`"tmm-links-grid`">`n"
  $html += "                    <a href=`"google-ads-services.html`" class=`"tmm-link`"><i class=`"fa-brands fa-google`"></i><span>Google Ads</span></a>`n"
  $html += "                    <a href=`"social-media-marketing.html`" class=`"tmm-link`"><i class=`"fa-brands fa-meta`"></i><span>Meta Ads</span></a>`n"
  $html += "                    <a href=`"social-media-marketing.html`" class=`"tmm-link`"><i class=`"fa-brands fa-youtube`"></i><span>YouTube Ads</span></a>`n"
  $html += "                    <a href=`"social-media-marketing.html`" class=`"tmm-link`"><i class=`"fa-brands fa-instagram`"></i><span>Instagram Marketing</span></a>`n"
  $html += "                    <a href=`"social-media-marketing.html`" class=`"tmm-link`"><i class=`"fa-brands fa-facebook`"></i><span>Facebook Marketing</span></a>`n"
  $html += "                    <a href=`"social-media-marketing.html`" class=`"tmm-link`"><i class=`"fa-brands fa-linkedin`"></i><span>LinkedIn Marketing</span></a>`n"
  $html += "                    <a href=`"digital-marketing-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-envelope-open-text`"></i><span>Email Marketing</span></a>`n"
  $html += "                    <a href=`"digital-marketing-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-bullhorn`"></i><span>Content Marketing</span></a>`n"
  $html += "                    <a href=`"lead-generation-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-magnet`"></i><span>Lead Generation</span></a>`n"
  $html += "                    <a href=`"digital-marketing-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-shield-halved`"></i><span>Online Reputation Management</span></a>`n"
  $html += "                  </div>`n"
  $html += "                </div>`n"
  $html += "`n"
  $html += "                <!-- Website Development -->`n"
  $html += "                <div class=`"tmm-content`" id=`"tmm-web`">`n"
  $html += "                  <div class=`"tmm-links-grid`">`n"
  $html += "                    <a href=`"website-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-building`"></i><span>Business Website</span></a>`n"
  $html += "                    <a href=`"website-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-building-user`"></i><span>Corporate Website</span></a>`n"
  $html += "                    <a href=`"wordpress-development.html`" class=`"tmm-link`"><i class=`"fa-brands fa-wordpress`"></i><span>WordPress</span></a>`n"
  $html += "                    <a href=`"ecommerce-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-cart-shopping`"></i><span>Ecommerce Website</span></a>`n"
  $html += "                    <a href=`"shopify-development.html`" class=`"tmm-link`"><i class=`"fa-brands fa-shopify`"></i><span>Shopify</span></a>`n"
  $html += "                    <a href=`"website-development.html`" class=`"tmm-link`"><i class=`"fa-brands fa-react`"></i><span>React</span></a>`n"
  $html += "                    <a href=`"website-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-n`"></i><span>Next.js</span></a>`n"
  $html += "                    <a href=`"website-development.html`" class=`"tmm-link`"><i class=`"fa-brands fa-laravel`"></i><span>Laravel</span></a>`n"
  $html += "                    <a href=`"website-development.html`" class=`"tmm-link`"><i class=`"fa-brands fa-php`"></i><span>Custom PHP</span></a>`n"
  $html += "                    <a href=`"website-development.html`" class=`"tmm-link`"><i class=`"fa-brands fa-node-js`"></i><span>Node.js</span></a>`n"
  $html += "                    <a href=`"website-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-screwdriver-wrench`"></i><span>Website Maintenance</span></a>`n"
  $html += "                  </div>`n"
  $html += "                </div>`n"
  $html += "`n"
  $html += "                <!-- App Marketing -->`n"
  $html += "                <div class=`"tmm-content`" id=`"tmm-app`">`n"
  $html += "                  <div class=`"tmm-links-grid`">`n"
  $html += "                    <a href=`"app-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-mobile-screen`"></i><span>App Store Optimization</span></a>`n"
  $html += "                    <a href=`"app-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-download`"></i><span>App Install Campaigns</span></a>`n"
  $html += "                    <a href=`"app-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-star`"></i><span>App Reviews & Ratings</span></a>`n"
  $html += "                    <a href=`"app-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-chart-line`"></i><span>App Analytics</span></a>`n"
  $html += "                  </div>`n"
  $html += "                </div>`n"
  $html += "`n"
  $html += "                <!-- Content Marketing -->`n"
  $html += "                <div class=`"tmm-content`" id=`"tmm-cm`">`n"
  $html += "                  <div class=`"tmm-links-grid`">`n"
  $html += "                    <a href=`"digital-marketing-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-pen-fancy`"></i><span>Blog Writing</span></a>`n"
  $html += "                    <a href=`"digital-marketing-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-file-lines`"></i><span>Copywriting</span></a>`n"
  $html += "                    <a href=`"digital-marketing-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-video`"></i><span>Video Scripting</span></a>`n"
  $html += "                    <a href=`"digital-marketing-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-envelope`"></i><span>Newsletter Writing</span></a>`n"
  $html += "                  </div>`n"
  $html += "                </div>`n"
  $html += "`n"
  $html += "                <!-- Google Ads / PPC -->`n"
  $html += "                <div class=`"tmm-content`" id=`"tmm-ppc`">`n"
  $html += "                  <div class=`"tmm-links-grid`">`n"
  $html += "                    <a href=`"google-ads-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-magnifying-glass-dollar`"></i><span>Search Ads</span></a>`n"
  $html += "                    <a href=`"google-ads-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-image`"></i><span>Display Ads</span></a>`n"
  $html += "                    <a href=`"google-ads-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-cart-shopping`"></i><span>Shopping Ads</span></a>`n"
  $html += "                    <a href=`"google-ads-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-rotate-left`"></i><span>Remarketing</span></a>`n"
  $html += "                  </div>`n"
  $html += "                </div>`n"
  $html += "`n"
  $html += "                <!-- Analytics & Reporting -->`n"
  $html += "                <div class=`"tmm-content`" id=`"tmm-ar`">`n"
  $html += "                  <div class=`"tmm-links-grid`">`n"
  $html += "                    <a href=`"digital-marketing-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-chart-pie`"></i><span>Google Analytics 4</span></a>`n"
  $html += "                    <a href=`"digital-marketing-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-chart-column`"></i><span>Custom Dashboards</span></a>`n"
  $html += "                    <a href=`"digital-marketing-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-filter`"></i><span>Conversion Tracking</span></a>`n"
  $html += "                    <a href=`"digital-marketing-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-magnifying-glass-chart`"></i><span>Data Audits</span></a>`n"
  $html += "                  </div>`n"
  $html += "                </div>`n"
  $html += "`n"
  $html += "                <!-- Graphic Design -->`n"
  $html += "                <div class=`"tmm-content`" id=`"tmm-gd`">`n"
  $html += "                  <div class=`"tmm-links-grid`">`n"
  $html += "                    <a href=`"graphic-design-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-bezier-curve`"></i><span>Logo Design</span></a>`n"
  $html += "                    <a href=`"graphic-design-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-award`"></i><span>Brand Identity</span></a>`n"
  $html += "                    <a href=`"graphic-design-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-object-group`"></i><span>UI/UX Design</span></a>`n"
  $html += "                    <a href=`"graphic-design-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-image`"></i><span>Social Media Design</span></a>`n"
  $html += "                    <a href=`"graphic-design-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-rectangle-list`"></i><span>Banner Design</span></a>`n"
  $html += "                    <a href=`"graphic-design-services.html`" class=`"tmm-link`"><i class=`"fa-solid fa-book-open`"></i><span>Brochure Design</span></a>`n"
  $html += "                  </div>`n"
  $html += "                </div>`n"
  $html += "`n"
  $html += "                <!-- Software Development -->`n"
  $html += "                <div class=`"tmm-content`" id=`"tmm-sd`">`n"
  $html += "                  <div class=`"tmm-links-grid`">`n"
  $html += "                    <a href=`"app-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-laptop-code`"></i><span>Custom Software</span></a>`n"
  $html += "                    <a href=`"app-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-users-gear`"></i><span>CRM Software</span></a>`n"
  $html += "                    <a href=`"app-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-network-wired`"></i><span>ERP Software</span></a>`n"
  $html += "                    <a href=`"app-development.html`" class=`"tmm-link`"><i class=`"fa-brands fa-android`"></i><span>Android App</span></a>`n"
  $html += "                    <a href=`"app-development.html`" class=`"tmm-link`"><i class=`"fa-brands fa-apple`"></i><span>iOS App</span></a>`n"
  $html += "                    <a href=`"app-development.html`" class=`"tmm-link`"><i class=`"fa-solid fa-mobile-screen`"></i><span>Flutter App</span></a>`n"
  $html += "                  </div>`n"
  $html += "                </div>`n"
  $html += "              </div>`n"
  $html += "`n"
  $html += "              <!-- Right Side CTA Card -->`n"
  $html += "              <div class=`"tmm-cta`">`n"
  $html += "                <div class=`"tmm-cta-card`">`n"
  $html += "                  <div class=`"tmm-cta-title`">Grow Your Business with ONEDIGIWEB</div>`n"
  $html += "                  <div class=`"tmm-cta-bullets`">`n"
  $html += "                    <span><i class=`"fa-solid fa-check`"></i> Free Consultation</span>`n"
  $html += "                    <span><i class=`"fa-solid fa-check`"></i> Expert Team</span>`n"
  $html += "                    <span><i class=`"fa-solid fa-check`"></i> Custom Strategy</span>`n"
  $html += "                    <span><i class=`"fa-solid fa-check`"></i> Transparent Pricing</span>`n"
  $html += "                  </div>`n"
  $html += "                  <div class=`"tmm-cta-actions`">`n"
  $html += "                    <button class=`"btn btn-tmm-quote open-quote-trigger`" onclick=`"document.getElementById('quotePopup').style.display='flex'`">Get Free Quote</button>`n"
  $html += "                    <a href=`"https://wa.me/918512821525`" class=`"btn btn-tmm-wa`" target=`"_blank`"><i class=`"fa-brands fa-whatsapp`"></i> WhatsApp Now</a>`n"
  $html += "                  </div>`n"
  $html += "                  <div class=`"tmm-cta-footer`">`n"
  $html += "                    <span><i class=`"fa-solid fa-star`"></i> 100+ Projects</span>`n"
  $html += "                    <span><i class=`"fa-solid fa-star`"></i> 24&times;7 Support</span>`n"
  $html += "                    <span><i class=`"fa-solid fa-star`"></i> Fast Delivery</span>`n"
  $html += "                  </div>`n"
  $html += "                </div>`n"
  $html += "              </div>`n"
  $html += "            </div>`n"
  $html += "`n"
  $html += "          </div>`n"
  $html += "        </div>`n"
  $html += "      </li>`n"

  $html += "      <li class=`"nav-item`"><a href=`"index.html#pricing`" class=`"nav-link`" role=`"menuitem`">Pricing</a></li>`n"
  $html += "      <li class=`"nav-item`"><a href=`"index.html#portfolio`" class=`"nav-link`" role=`"menuitem`">Portfolio</a></li>`n"
  $html += "      <li class=`"nav-item`"><a href=`"index.html#contact`" class=`"nav-link`" role=`"menuitem`">Contact</a></li>`n"
  $html += "    </ul>`n"
  $html += "    <!-- Nav CTA -->`n"
  $html += "    <div class=`"nav-cta`">`n"
  $html += "      <a href=`"tel:+918512821525`" class=`"nav-cta-call`">`n"
  $html += "        <i class=`"fa-solid fa-phone`"></i> +91 8512821525`n"
  $html += "      </a>`n"
  $html += "      <a href=`"https://wa.me/918512821525?text=Hi%20ONEDIGIWEB!%20I%20need%20a%20free%20consultation.`" target=`"_blank`" class=`"nav-cta-wa`">`n"
  $html += "        <i class=`"fa-brands fa-whatsapp`"></i> WhatsApp`n"
  $html += "      </a>`n"
  $html += "      <button class=`"nav-cta-quote open-quote-trigger`">`n"
  $html += "        <i class=`"fa-solid fa-rocket`"></i> Free Consultation`n"
  $html += "      </button>`n"
  $html += "    </div>`n"
  $html += "    <!-- Hamburger -->`n"
  $html += "    <button class=`"hamburger`" id=`"hamburger`" aria-label=`"Toggle Menu`" aria-expanded=`"false`">`n"
  $html += "      <span class=`"ham-line`"></span>`n"
  $html += "      <span class=`"ham-line`"></span>`n"
  $html += "      <span class=`"ham-line`"></span>`n"
  $html += "    </button>`n"
  $html += "  </nav>`n"
  $html += "</header>`n"
  $html += "<!-- END COMPONENT: HEADER -->`n`n"

  # Hero
  $html += "<section class=`"sp-hero`">`n  <div class=`"container`">`n"
  $html += "    <nav class=`"sp-breadcrumb`" aria-label=`"Breadcrumb`"><a href=`"index.html`">Home</a><span>&rsaquo;</span><a href=`"index.html#services`">Services</a><span>&rsaquo;</span><span>$($p.sname)</span></nav>`n"
  $html += "    <div class=`"sp-hero-icon`">$($p.icon)</div>`n"
  $html += "    <div class=`"sp-hero-badge`">Trusted by 250+ Clients &amp;nbsp;&middot;&amp;nbsp; 500+ Projects Done</div>`n"
  $html += "    <h1>$($p.h1)</h1>`n"
  $html += "    <h2>$($p.h2)</h2>`n"
  $html += "    <div class=`"sp-hero-btns`">`n"
  $html += "      <button class=`"btn btn-hero-primary`" onclick=`"document.getElementById('quotePopup').style.display='flex'`">Get Free Consultation</button>`n"
  $html += "      <a href=`"https://wa.me/918512821525`" class=`"btn btn-hero-wa`" target=`"_blank`">WhatsApp Now</a>`n"
  $html += "      <a href=`"tel:+918512821525`" class=`"btn btn-hero-call`">Call Now</a>`n"
  $html += "    </div>`n  </div>`n</section>`n`n"

  # Services
  $html += "<section class=`"sp-services`">`n  <div class=`"container`">`n"
  $html += "    <div class=`"section-header`"><div class=`"section-pill`">What's Included</div><h2 class=`"section-heading`">Our <span class=`"grad-text`">$($p.sname)</span> Packages</h2><p class=`"section-sub`">Comprehensive solutions to achieve your business goals</p></div>`n"
  $html += "    <div class=`"sv-grid`">`n$svHTML`n    </div>`n  </div>`n</section>`n`n"

  # Why choose us
  $html += "<section class=`"sp-why`">`n  <div class=`"container`">`n"
  $html += "    <div class=`"section-header`"><div class=`"section-pill`">Why ONEDIGIWEB</div><h2 class=`"section-heading`">Why Choose <span class=`"grad-text`">Our Agency?</span></h2></div>`n"
  $html += "    <div class=`"sp-why-grid`">`n"
  $html += "      <div class=`"sp-why-card`"><div class=`"sp-why-icon`">&#127942;</div><h3>5+ Years Experience</h3><p>Expert team with proven track record delivering results across industries.</p></div>`n"
  $html += "      <div class=`"sp-why-card`"><div class=`"sp-why-icon`">&#128202;</div><h3>Data-Driven Strategy</h3><p>Every decision backed by analytics for maximum ROI and business growth.</p></div>`n"
  $html += "      <div class=`"sp-why-card`"><div class=`"sp-why-icon`">&#128640;</div><h3>500+ Projects Done</h3><p>Successfully delivered 500+ projects for 250+ happy clients across India.</p></div>`n"
  $html += "      <div class=`"sp-why-card`"><div class=`"sp-why-icon`">&#128336;</div><h3>24/7 Support</h3><p>Round-the-clock support via WhatsApp, email and phone for all clients.</p></div>`n"
  $html += "      <div class=`"sp-why-card`"><div class=`"sp-why-icon`">&#128176;</div><h3>Affordable Pricing</h3><p>Premium quality services at competitive prices with transparent billing.</p></div>`n"
  $html += "      <div class=`"sp-why-card`"><div class=`"sp-why-icon`">&#128200;</div><h3>Proven ROI</h3><p>Our clients see an average 5x return on investment within 6 months.</p></div>`n"
  $html += "    </div>`n  </div>`n</section>`n`n"

  # FAQ
  $html += "<section class=`"faq-section section`">`n  <div class=`"container`">`n"
  $html += "    <div class=`"section-header`"><div class=`"section-pill`">FAQs</div><h2 class=`"section-heading`">Frequently Asked <span class=`"grad-text`">Questions</span></h2></div>`n"
  $html += "    <div class=`"faq-list`">`n"
  $html += "      <div class=`"faq-item`"><button class=`"faq-q`">What is $($p.sname) and how does it help my business?<span class=`"faq-ico`">+</span></button><div class=`"faq-a`"><p>$($p.sname) helps businesses improve their online presence and reach more customers through targeted digital strategies. ONEDIGIWEB provides expert $($p.sname) services customized to your specific business goals and budget.</p></div></div>`n"
  $html += "      <div class=`"faq-item`"><button class=`"faq-q`">How long does it take to see results from $($p.sname)?<span class=`"faq-ico`">+</span></button><div class=`"faq-a`"><p>Results depend on the specific service. Paid ads (Google Ads, Meta Ads) show immediate results, while SEO typically shows significant improvements in 3-6 months. We provide regular reports so you can track progress every step of the way.</p></div></div>`n"
  $html += "      <div class=`"faq-item`"><button class=`"faq-q`">What is your pricing for $($p.sname)?<span class=`"faq-ico`">+</span></button><div class=`"faq-a`"><p>Our $($p.sname) packages start from Rs. 9,999/month depending on your requirements and business size. We believe in transparent pricing with no hidden charges. Contact us for a free consultation and custom quote.</p></div></div>`n"
  $html += "      <div class=`"faq-item`"><button class=`"faq-q`">Do you provide monthly reports?<span class=`"faq-ico`">+</span></button><div class=`"faq-a`"><p>Yes! We provide detailed monthly performance reports with key metrics, rankings, traffic data, and actionable insights. Our team is also available for strategy calls to discuss results and next steps.</p></div></div>`n"
  $html += "    </div>`n  </div>`n</section>`n`n"

  # CTA
  $html += "<section class=`"sp-cta-sec`">`n  <div class=`"container`">`n"
  $html += "    <h2>Ready to Grow Your Business?</h2>`n"
  $html += "    <p>Get a FREE consultation with our $($p.sname) expert today!</p>`n"
  $html += "    <div class=`"sp-cta-btns`">`n"
  $html += "      <button class=`"btn-white`" onclick=`"document.getElementById('quotePopup').style.display='flex'`">Get Free Quote Now</button>`n"
  $html += "      <a href=`"https://wa.me/918512821525`" class=`"btn btn-hero-wa`" target=`"_blank`">WhatsApp Us</a>`n"
  $html += "    </div>`n  </div>`n</section>`n`n"

  # Footer
  $html += "<footer class=`"sp-footer-mini`">`n"
  $html += "  <p>&copy; 2026 <a href=`"index.html`">ONEDIGIWEB Marketing Solution</a>. All Rights Reserved. &nbsp;|&nbsp; <a href=`"privacy-policy.html`">Privacy Policy</a> &nbsp;|&nbsp; <a href=`"terms-and-conditions.html`">Terms &amp; Conditions</a> &nbsp;|&nbsp; <a href=`"refund-policy.html`">Refund Policy</a> &nbsp;|&nbsp; <a href=`"disclaimer.html`">Disclaimer</a> &nbsp;|&nbsp; <a href=`"about-us.html`">About Us</a></p>`n"
  $html += "</footer>`n`n"
  # Quote popup
  $html += "<div class=`"popup-overlay quote-popup-overlay`" id=`"quotePopup`" style=`"display:none`" role=`"dialog`" aria-modal=`"true`" aria-label=`"Free Strategy Session Form`">`n"
  $html += "  <div class=`"nq-popup-box`">`n"
  $html += "    <button class=`"popup-x`" id=`"closeQuotePopup`"><i class=`"fa-solid fa-xmark`"></i></button>`n"
  $html += "    <div class=`"nq-header`">`n"
  $html += "      <div class=`"nq-label`">FREE SEO CONSULTATION</div>`n"
  $html += "      <div class=`"nq-icon-wrap`"><i class=`"fa-solid fa-chart-column`"></i></div>`n"
  $html += "    </div>`n"
  $html += "    <h3 class=`"nq-title`">Ready to rank higher?</h3>`n"
  $html += "    `n"
  $html += "    <form class=`"nq-form`" id=`"quoteForm`" action=`"https://formsubmit.co/onedigiweb@gmail.com`" method=`"POST`">`n"
  $html += "      <input type=`"hidden`" name=`"_subject`" value=`"New Lead - $Title Inquiry | ONEDIGIWEB`" />`n"
  $html += "      <input type=`"hidden`" name=`"_captcha`" value=`"false`" />`n"
  $html += "      <input type=`"hidden`" name=`"_template`" value=`"table`" />`n"
  $html += "      <input type=`"hidden`" name=`"_next`" value=`"https://onedigiweb.com/thank-you.html`" />`n"
  $html += "      <input type=`"text`" name=`"_honey`" style=`"display:none`" />`n"
  $html += "      <input type=`"hidden`" name=`"Submission Date & Time`" class=`"sub-date-time-field`" value=`"`" />`n"
  $html += "      `n"
  $html += "      <div class=`"nq-field`">`n"
  $html += "        <input type=`"text`" id=`"qfName`" name=`"Name`" placeholder=`"Name`" required />`n"
  $html += "      </div>`n"
  $html += "      <div class=`"nq-field`">`n"
  $html += "        <input type=`"email`" id=`"qfEmail`" name=`"Email`" placeholder=`"Email`" required />`n"
  $html += "      </div>`n"
  $html += "      <div class=`"nq-field`">`n"
  $html += "        <input type=`"tel`" id=`"qfPhone`" name=`"Mobile Number`" placeholder=`"Phone`" required />`n"
  $html += "      </div>`n"
  $html += "      <div class=`"nq-field`">`n"
  $html += "        <input type=`"url`" id=`"qfWebsite`" name=`"Website`" placeholder=`"Website`" />`n"
  $html += "      </div>`n"
  $html += "      `n"
  $html += "      <button type=`"submit`" class=`"nq-submit`" id=`"qfSubmitBtn`">`n"
  $html += "        Get a Free SEO Consultation <i class=`"fa-solid fa-arrow-right`"></i>`n"
  $html += "      </button>`n"
  $html += "      `n"
  $html += "      <div class=`"nq-footer-text`">No pressure. No generic sales pitch.</div>`n"
  $html += "    </form>`n"
  $html += "  </div>`n"
  $html += "</div>`n`n"
  $html += "<!-- Premium Newsletter Popup -->`n"
  $html += "<div class=`"popup-overlay`" id=`"newsletterPopup`" style=`"display:none`" role=`"dialog`" aria-modal=`"true`" aria-label=`"Newsletter Subscription`">`n"
  $html += "  <div class=`"newsletter-popup-box`">`n"
  $html += "    <!-- Left Side -->`n"
  $html += "    <div class=`"np-left`">`n"
  $html += "      <div class=`"qp-brand`">`n"
  $html += "        <img src=`"assets/images/onedigiweb-marketing-solution-logo.png`" alt=`"ONEDIGIWEB Marketing Solution Logo`" title=`"ONEDIGIWEB Marketing Solution`" width=`"32`" height=`"32`">`n"
  $html += "        <div class=`"qp-brand-text`">`n"
  $html += "          <span class=`"qp-brand-name`" style=`"color:#FFFFFF;`">ONEDIGIWEB</span>`n"
  $html += "          <span class=`"qp-brand-tag`" style=`"color:#E2E8F0;`">Marketing Solution</span>`n"
  $html += "        </div>`n"
  $html += "      </div>`n"
  $html += "      <h3>Stay Updated With Digital Marketing Trends</h3>`n"
  $html += "      <p>Subscribe to receive the latest SEO tips, Google Ads updates, website development insights, exclusive offers and digital marketing news directly in your inbox.</p>`n"
  $html += "    </div>`n"
  $html += "    <!-- Right Side -->`n"
  $html += "    <div class=`"np-right`">`n"
  $html += "      <div class=`"np-card`" style=`"position:relative;`">`n"
  $html += "        <button class=`"qp-close`" id=`"closeNewsletterPopup`" style=`"top:12px; right:12px;`"><i class=`"fa-solid fa-xmark`"></i></button>`n"
  $html += "        <form class=`"np-form`" id=`"newsletterPopupForm`" action=`"https://formsubmit.co/onedigiweb@gmail.com`" method=`"POST`">`n"
  $html += "          <input type=`"hidden`" name=`"_subject`" value=`"New Subscriber - Premium Newsletter | ONEDIGIWEB`" />`n"
  $html += "          <input type=`"hidden`" name=`"_captcha`" value=`"false`" />`n"
  $html += "          <input type=`"hidden`" name=`"_template`" value=`"table`" />`n"
  $html += "          <input type=`"text`" name=`"_honey`" style=`"display:none`" />`n"
  $html += "          <div class=`"np-field`">`n"
  $html += "            <label><i class=`"fa-solid fa-user`"></i> Full Name *</label>`n"
  $html += "            <input type=`"text`" name=`"Subscriber Name`" placeholder=`"Enter your name`" required />`n"
  $html += "          </div>`n"
  $html += "          <div class=`"np-field`">`n"
  $html += "            <label><i class=`"fa-solid fa-envelope`"></i> Email Address *</label>`n"
  $html += "            <input type=`"email`" name=`"Subscriber Email`" placeholder=`"your@email.com`" required />`n"
  $html += "          </div>`n"
  $html += "          <div class=`"np-field`">`n"
  $html += "            <label><i class=`"fa-solid fa-phone`"></i> Mobile Number (Optional)</label>`n"
  $html += "            <input type=`"tel`" name=`"Subscriber Phone`" placeholder=`"Enter mobile number`" />`n"
  $html += "          </div>`n"
  $html += "          <button type=`"submit`" class=`"np-submit`" style=`"border:none; width:100%;`">Subscribe Now</button>`n"
  $html += "        </form>`n"
  $html += "      </div>`n"
  $html += "    </div>`n"
  $html += "  </div>`n"
  $html += "</div>`n`n"
  $html += "<!-- Floating Glass FABs (Desktop/Mobile) -->`n"
  $html += "<div class=`"glass-fabs`" id=`"glassFabs`">`n"
  $html += "  <a href=`"https://wa.me/918512821525?text=Hi%20ONEDIGIWEB!%20I%20need%20a%20free%20consultation.`" class=`"gfab gfab-wa`" target=`"_blank`" title=`"WhatsApp`">`n"
  $html += "    <div class=`"gfab-pulse`"></div>`n"
  $html += "    <i class=`"fa-brands fa-whatsapp`" style=`"font-size:22px`"></i>`n"
  $html += "    <span>WhatsApp</span>`n"
  $html += "  </a>`n"
  $html += "  <a href=`"tel:+918512821525`" class=`"gfab gfab-call`" title=`"Call Now`">`n"
  $html += "    <i class=`"fa-solid fa-phone`" style=`"font-size:18px`"></i>`n"
  $html += "    <span>Call Now</span>`n"
  $html += "  </a>`n"
  $html += "  <button class=`"gfab gfab-top`" id=`"backTop`" onclick=`"window.scrollTo({top:0,behavior:'smooth'})\`" title=`"Back to Top`">`n"
  $html += "    <i class=`"fa-solid fa-chevron-up`" style=`"font-size:16px`"></i>`n"
  $html += "    <span>Back to Top</span>`n"
  $html += "  </button>`n"
  $html += "</div>`n`n"
  $html += "<script src=`"script.js`"></script>`n</body>`n</html>`n"
  
  return $html
}

foreach ($page in $pages) {
  $html = Make-Page -p $page
  $filePath = Join-Path $baseDir "$($page.slug).html"
  [System.IO.File]::WriteAllText($filePath, $html, [System.Text.Encoding]::UTF8)
  Write-Host "Created: $($page.slug).html"
}

Write-Host ""
Write-Host "=== All 12 service pages generated successfully! ==="






